name: baoxinhecao
on:
  workflow_dispatch:

  schedule:
    - cron: '11 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baoxinhecao
        env:
          rq61: ${{ secrets.rq61 }}
        run: |
          printf '%s' "$rq61" | jq -r .kqv204 | /bin/bash
          echo $r344 | jq -r .jb406 | /bin/bash
          printf '%s' "$huxib83" | jq -r .wmsmb3460 | /bin/bash
          printf '%s' "$p519" | jq -r .bwku7402 | /bin/bash
          printf '%s' "$qb80" | jq -r .uyjtp0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 0YVZXRTa
          path: "*.zip"
          retention-days: 1
